[package]
name = "SafeManuallyDrop"
version = "0.1.1"
authors = ["Денис Котляров <denis2005991@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
