[package]
name = "SafeManuallyDrop"
version = "0.1.5"
authors = ["Denis Kotlyarov <denis2005991@gmail.com>"]
edition = "2021"

[features]
default = [
	"always_check_in_case_debug_assertions", 
	"enable_deprecated_hook",
	
	"support_panic_trig", 
	"support_hook_trig" #,
	#"support_count_trig"
]
always_check_in_case_debug_assertions = []
always_safe_manuallydrop = []

support_hook_trig = []
support_count_trig = []
support_panic_trig = []

enable_deprecated_hook = []

[dependencies]
